name: berana
description: Berana.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  observable_ish: ^4.0.8
  loader_overlay: ^2.2.0
  http: ^0.13.5
  google_fonts: ^4.0.4
  get_storage: ^2.1.1
  stacked: 3.1.0
  get_it: 7.2.0
  auto_size_text: ^3.0.0
  video_player: ^2.6.1
  scroll_snap_list: ^0.9.1
  webview_flutter:  3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/bg/
   - assets/icons/flags/
   - assets/cover_art/